version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Rome
    open-pull-requests-limit: 5
    groups:
      development-patch-minor:
        dependency-type: development
        update-types:
          - minor
          - patch
      production-patch-minor:
        dependency-type: production
        update-types:
          - minor
          - patch
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Rome
    open-pull-requests-limit: 3
    groups:
      workflow-actions:
        patterns:
          - "*"
