// Each project carries three manual signals (not git-derived):
//   effort     1-5  how much total work went in
//   difficulty 1-5  how technically hard it was
//   focus      "now" | "shipped" | "earlier"  how current the focus is
// The /projects page groups by `focus` (NOW -> SHIPPED -> EARLIER) and sorts
// within each group by effort desc. See pages/projects.js.
const projectData = [
  {
    id: "buildlog",
    title: "Buildlog",
    description:
      "My build-in-public dev journal. A tiny Rails app where I post what I ship each day. Not a product, a forcing function for daily shipping and the raw material for the weekly articles.",
    thumbnail: "/thumbs/buildlog.svg",
    socialImage: "/thumbs/buildlog-social.png",
    stack: ["Ruby on Rails", "SQLite", "Kamal", "DaisyUI"],
    github: "https://github.com/ozzgio/buildlog",
    demo: "https://log.ozzo.blog",
    date: "2026-07",
    tags: ["Full Stack", "Rails"],
    effort: 3,
    difficulty: 2,
    focus: "now",
  },
  {
    id: "synergym",
    title: "Synergym.fit",
    description:
      "Gym management SaaS for trainers and athletes. Program creation, exercise library, athlete tracking, role-based access. Rails 8, PostgreSQL, Sidekiq, Playwright. In production since late 2025. No active users yet. Distribution is still the unsolved half.",
    thumbnail: "/thumbs/synergym.png",
    stack: ["Ruby on Rails", "PostgreSQL", "Redis", "Sidekiq", "Tailwind CSS"],
    github: null,
    demo: "https://synergym.fit",
    date: "2025-10",
    tags: ["Full Stack", "Rails"],
    effort: 5,
    difficulty: 5,
    focus: "shipped",
  },
  {
    id: "homelab",
    title: "NUC Homelab",
    description:
      "Intel NUC14 running Linux and 25+ Docker services. Self-hosted git and CI with Gitea, local inference with Ollama, n8n for automation, ChromaDB for vectors, Faster-Whisper for speech-to-text. A custom MCP server connects the Obsidian vault to AI agents. Private repos, self-hosted on Gitea. Infrastructure for personal autonomy, not meant as a demo.",
    thumbnail: "/thumbs/homelab.svg",
    stack: ["Docker", "Linux", "Gitea", "n8n", "Ollama"],
    github: null,
    demo: null,
    date: "2024-01",
    tags: ["DevOps", "Infrastructure"],
    effort: 5,
    difficulty: 4,
    focus: "shipped",
  },
  {
    id: "agentic-hub",
    title: "Agentic Hub",
    description:
      "Personal ops dashboard running on the NUC. Chat, tasks board, fleet view for cron jobs, Telegram topics, wiki, terminal. Built against the Hermes open-source gateway API. Next.js 15, Tailwind, shadcn/ui.",
    thumbnail: "/thumbs/agentic-hub.svg",
    stack: ["Next.js", "Tailwind CSS", "TypeScript", "shadcn/ui"],
    github: null,
    demo: null,
    date: "2026-01",
    tags: ["Full Stack", "Next.js"],
    effort: 4,
    difficulty: 4,
    focus: "shipped",
  },
  {
    id: "portfolio",
    title: "This Site",
    description:
      "Next.js 15, Chakra UI, Framer Motion. Articles and book notes sync from Obsidian via a Python script and GitHub Actions pipeline. Still being improved; this is where the writing and the UI experiments live.",
    thumbnail: "/thumbs/portfolio.png",
    stack: ["Next.js", "Chakra UI", "Framer Motion", "GitHub Actions"],
    github: "https://github.com/ozzgio/ozzoblog",
    demo: "https://ozzo.blog",
    date: "2023-05",
    tags: ["Frontend", "Next.js"],
    effort: 4,
    difficulty: 3,
    focus: "shipped",
  },
  {
    id: "rubychess",
    title: "Ruby Chess",
    description:
      "Full chess in the terminal, written in pure Ruby. OOP design, RSpec coverage, castling, en passant, pawn promotion, PGN export. Built as the final project for the Odin Project Ruby curriculum.",
    thumbnail: "/thumbs/rubychess.png",
    stack: ["Ruby"],
    github: "https://github.com/ozzgio/ruby_chess",
    demo: null,
    date: "2025-05",
    tags: ["Ruby"],
    effort: 3,
    difficulty: 3,
    focus: "earlier",
  },
  {
    id: "meteomapbot",
    title: "MeteoMap Bot",
    description:
      "Telegram bot for Italian weather. Node.js, OpenWeatherMap API, SQL Server for regions and city data. Interactive keyboards, location sharing. Still running.",
    thumbnail: "/thumbs/meteomapbot.png",
    stack: ["Node.js", "JavaScript", "Telegram API"],
    github: "https://gist.github.com/ozzgio/2a1f1d2cff1a9134a50ad5c94c451e35",
    demo: "https://t.me/meteomapbot",
    date: "2024-08",
    tags: ["Backend", "Node.js"],
    effort: 2,
    difficulty: 2,
    focus: "earlier",
  },
  {
    id: "kellyspub",
    title: "Kelly's Pub",
    description:
      "WordPress site for a local pub. Content, plugins, custom styling. Still live.",
    thumbnail: "/thumbs/kellyspub.png",
    stack: ["WordPress", "PHP", "MySQL"],
    github: null,
    demo: "https://birreriakellys.it",
    date: "2024-06",
    tags: ["WordPress"],
    effort: 2,
    difficulty: 3,
    focus: "earlier",
  },
  {
    id: "fbetsui",
    title: "FootballBets UI",
    description:
      "Angular frontend for a football betting tracker. TypeScript, SCSS. On hold; stopped to reposition, might come back as a local-only version.",
    thumbnail: "/thumbs/fbetsui.png",
    stack: ["Angular", "TypeScript", "SCSS"],
    github: "https://github.com/ozzgio/FootballBetsUI",
    demo: null,
    date: "2024-03",
    tags: ["Frontend", "Angular"],
    effort: 3,
    difficulty: 4,
    focus: "earlier",
  },
  {
    id: "fbetsapi",
    title: "FootballBets API",
    description:
      "C# REST API backing the football betting tracker. SQLite, Docker. Paused alongside the frontend.",
    thumbnail: "/thumbs/fbetsapi.png",
    stack: ["C#", "SQLite", "Docker"],
    github: "https://github.com/ozzgio/FootballBetsAPI",
    demo: null,
    date: "2024-02",
    tags: ["Backend", "C#"],
    effort: 3,
    difficulty: 4,
    focus: "earlier",
  },
];

export default projectData;
