const projectData = [
  {
    id: "synergym",
    title: "Synergym.fit",
    description:
      "Gym management SaaS for trainers and athletes. Program creation, exercise library, athlete tracking, role-based access. Rails 8, PostgreSQL, Sidekiq, Playwright. In production since late 2025. No active users yet. Distribution is still the unsolved half.",
    thumbnail: "/thumbs/synergym.png",
    stack: ["Ruby on Rails", "PostgreSQL", "Redis", "Sidekiq", "Tailwind CSS"],
    github: null,
    demo: "https://synergym.fit",
    date: "2025-10",
    tags: ["Full Stack", "Rails"],
    status: "featured",
  },
  {
    id: "agentic-hub",
    title: "Agentic Hub",
    description:
      "Personal ops dashboard running on the NUC. Chat, tasks board, fleet view for cron jobs, Telegram topics, wiki, terminal. Built against the Hermes open-source gateway API. Next.js 15, Tailwind, shadcn/ui.",
    thumbnail: "/thumbs/agentic-hub.svg",
    stack: ["Next.js", "Tailwind CSS", "TypeScript", "shadcn/ui"],
    github: null,
    demo: null,
    date: "2026-01",
    tags: ["Full Stack", "Next.js"],
    status: "active",
  },
  {
    id: "homelab",
    title: "NUC Homelab",
    description:
      "Intel NUC14 running Linux and 25+ Docker services. Self-hosted git and CI with Gitea, local inference with Ollama, n8n for automation, ChromaDB for vectors, Faster-Whisper for speech-to-text. A custom MCP server connects the Obsidian vault to AI agents. Private repos, self-hosted on Gitea. Infrastructure for personal autonomy, not meant as a demo.",
    thumbnail: "/thumbs/homelab.svg",
    stack: ["Docker", "Linux", "Gitea", "n8n", "Ollama"],
    github: null,
    demo: null,
    date: "2024-01",
    tags: ["DevOps", "Infrastructure"],
    status: "active",
  },
  {
    id: "rubychess",
    title: "Ruby Chess",
    description:
      "Full chess in the terminal, written in pure Ruby. OOP design, RSpec coverage, castling, en passant, pawn promotion, PGN export. Built as the final project for the Odin Project Ruby curriculum.",
    thumbnail: "/thumbs/rubychess.png",
    stack: ["Ruby"],
    github: "https://github.com/ozzgio/ruby_chess",
    demo: null,
    date: "2025-05",
    tags: ["Ruby"],
    status: "learning",
  },
  {
    id: "meteomapbot",
    title: "MeteoMap Bot",
    description:
      "Telegram bot for Italian weather. Node.js, OpenWeatherMap API, SQL Server for regions and city data. Interactive keyboards, location sharing. Still running.",
    thumbnail: "/thumbs/meteomapbot.png",
    stack: ["Node.js", "JavaScript", "Telegram API"],
    github: "https://gist.github.com/ozzgio/2a1f1d2cff1a9134a50ad5c94c451e35",
    demo: "https://t.me/meteomapbot",
    date: "2024-08",
    tags: ["Backend", "Node.js"],
    status: "learning",
  },
  {
    id: "portfolio",
    title: "This Site",
    description:
      "Next.js 15, Chakra UI, Framer Motion. Articles and book notes sync from Obsidian via a Python script and GitHub Actions pipeline. Still being improved; this is where the writing and the UI experiments live.",
    thumbnail: "/thumbs/portfolio.png",
    stack: ["Next.js", "Chakra UI", "Framer Motion", "GitHub Actions"],
    github: "https://github.com/ozzgio/devozzo-homepage",
    demo: null,
    date: "2023-05",
    tags: ["Frontend", "Next.js"],
    status: "active",
  },
  {
    id: "kellyspub",
    title: "Kelly\'s Pub",
    description:
      "WordPress site for a local pub. Content, plugins, custom styling. Still live.",
    thumbnail: "/thumbs/kellyspub.png",
    stack: ["WordPress", "PHP", "MySQL"],
    github: null,
    demo: "https://birreriakellys.it",
    date: "2024-06",
    tags: ["WordPress"],
    status: "learning",
  },
  {
    id: "fbetsui",
    title: "FootballBets UI",
    description:
      "Angular frontend for a football betting tracker. TypeScript, SCSS. On hold; stopped to reposition, might come back as a local-only version.",
    thumbnail: "/thumbs/fbetsui.png",
    stack: ["Angular", "TypeScript", "SCSS"],
    github: "https://github.com/ozzgio/FootballBetsUI",
    demo: null,
    date: "2024-03",
    tags: ["Frontend", "Angular"],
    status: "learning",
  },
  {
    id: "fbetsapi",
    title: "FootballBets API",
    description:
      "C# REST API backing the football betting tracker. SQLite, Docker. Paused alongside the frontend.",
    thumbnail: "/thumbs/fbetsapi.png",
    stack: ["C#", "SQLite", "Docker"],
    github: "https://github.com/ozzgio/FootballBetsAPI",
    demo: null,
    date: "2024-02",
    tags: ["Backend", "C#"],
    status: "learning",
  },
];

export default projectData;
